---

- debug:
    msg: "-> small only"
  tags: [print_action]

- name: Update repositories cache and install required packages
  become: True
  apt:
    pkg:
    - python3-pip
    - python3.9
    update_cache: yes


- name: Install pipenv
  become: true
  pip:
    name: pipenv
    executable: pip3


- name: Setup a venv folder
  file:
    path: "{{ remote.dir }}/code/.venv"
    state: directory
    mode: 0755

# XXX: This task is very slow at the moment
- name: install dependencies via pipenv
  command: pipenv install
  args:
    chdir: "{{ remote.dir }}/code"
  environment:
    LC_ALL: "C.UTF-8"
    LANG: "C.UTF-8"
