---

- assert:
    that:
    - remote_results_dir is defined
    - local_results_dir is defined

- name: Create local folder (for results)
  file:
    path: "{{ local_results_dir }}/server{{ idx }}"
    state: directory
    mode: 0755
  loop: "{{ groups[exp_server.host_group] }}" 
  loop_control:
    loop_var: host
    index_var: idx

- name: Create local folder (for results)
  file:
    path: "{{ local_results_dir }}/client{{ idx }}"
    state: directory
    mode: 0755
  loop: "{{ groups[exp_client.host_group] }}" 
  loop_control:
    loop_var: host
    index_var: idx

- name: Fetch Results (if experiment done)
  delegate_to: localhost
  local_action: command rsync -az "{{ host }}:{{ remote_results_dir }}/*" "{{ local_results_dir }}/server{{ idx }}"
  loop: "{{ groups[exp_server.host_group] }}" 
  loop_control:
    loop_var: host
    index_var: idx


- name: Fetch Results (if experiment done)
  delegate_to: localhost
  local_action: command rsync -az "{{ host }}:{{ remote_results_dir }}/*" "{{ local_results_dir }}/client{{ idx }}"
  loop: "{{ groups[exp_client.host_group] }}" 
  loop_control:
    loop_var: host
    index_var: idx

- name: Save the config of the job
  delegate_to: localhost
  template:
    src: config.yml.j2
    dest: "{{ local_results_dir }}/config.yml"
    mode:  0755